GATTServices = {"0":"Generic Access",
"1":"Alert Notification Service",
"2":"Automation IO",
"3":"Battery Service",
"4":"Blood Pressure",
"5":"Body Composition",
"6":"Bond Management Service",
"7":"Continuous Glucose Monitoring",
"8":"Current Time Service",
"9":"Cycling Power",
"10":"Cycling Speed and Cadence",
"11":"Device Information",
"12":"Environmental Sensing",
"13":"Fitness Machine",
"14":"Generic Attribute",
"15":"Glucose",
"16":"Health Thermometer",
"17":"Heart Rate",
"18":"HTTP Proxy",
"19":"Human Interface Device",
"20":"Immediate Alert",
"21":"Indoor Positioning",
"22":"Insulin Delivery",
"23":"Internet Protocol Support Service",
"24":"Link Loss",
"25":"Location and Navigation",
"26":"Mesh Provisioning Service",
"27":"Mesh Proxy Service",
"28":"Next DST Change Service",
"29":"Object Transfer Service",
"30":"Phone Alert Status Service",
"31":"Pulse Oximeter Service",
"32":"Reconnection Configuration",
"33":"Reference Time Update Service",
"34":"Running Speed and Cadence",
"35":"Scan Parameters",
"36":"Transport Discovery",
"37":"Tx Power",
"38":"User Data",
"39":"Weight Scale"}