GATTServices = ["Generic Access",
"Alert Notification Service",
"Automation IO",
"Battery Service",
"Blood Pressure",
"Body Composition",
"Bond Management Service",
"Continuous Glucose Monitoring",
"Current Time Service",
"Cycling Power",
"Cycling Speed and Cadence",
"Device Information",
"Environmental Sensing",
"Fitness Machine",
"Generic Attribute",
"Glucose",
"Health Thermometer",
"Heart Rate",
"HTTP Proxy",
"Human Interface Device",
"Immediate Alert",
"Indoor Positioning",
"Insulin Delivery",
"Internet Protocol Support Service",
"Link Loss",
"Location and Navigation",
"Mesh Provisioning Service",
"Mesh Proxy Service",
"Next DST Change Service",
"Object Transfer Service",
"Phone Alert Status Service",
"Pulse Oximeter Service",
"Reconnection Configuration",
"Reference Time Update Service",
"Running Speed and Cadence",
"Scan Parameters",
"Transport Discovery",
"Tx Power",
"User Data",
"Weight Scale"]